/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function FireworkSolidColored(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '3d/fireworks/COLORED-firework-solid.gltf', draco('/draco-gltf/'))
  
  // useFrame(state => {
  //   const x = (1 + state.mouse.y) / 5 
  //   const y = (1 + state.mouse.x) / 5
  //   group.current.rotation.x = x
  //   group.current.rotation.y = y
  // })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Default OBJ']}
        geometry={nodes['firework-solid'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}
