/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import useMousePosition from '../setup/useMousePosition.js'

export default function Firework(props) {
	const group = useRef()
	const { nodes, materials } = useGLTF('3d/fireworks/COLORED-firework-solid_shadeless.glb')

	let { x, y } = useMousePosition()

	useFrame(() => {
		const newX = (1 + y) / 2900
		const newY = (1 + x) / 2900

		if (!props.menuIsOpen) {
			group.current.rotation.x = newX / 2 - 0.1
			group.current.rotation.y = newY / 2 - 0.1
			group.current.position.z = -(newY * 25 - 1.9)
		}
	})

	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				geometry={nodes['firework-solid'].geometry}
				material={materials['Default OBJ']}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</group>
	)
}

// useGLTF.preload('/COLORED-firework-solid_shadeless-transformed.glb')
