/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import useMousePosition from '../setup/useMousePosition.js'

export default function Firework({url,...props}) {
	const group = useRef()
	console.log('url',url)
	const { nodes, materials } = useGLTF(`${url}`)

	let { x, y } = useMousePosition()

	const menuIsOpen = props.menuIsOpen
	const menuStateCurrentName = props.menuState.currentName

	useFrame(() => {
		const newX = (1 + y) / 2900
		const newY = (1 + x) / 2900

		if (!menuIsOpen && menuStateCurrentName === 'main') {
			group.current.rotation.x = newX / 2 - 0.1
			group.current.rotation.y = newY / 2 - 0.1
			group.current.position.z = -(newY * 25 - 1.9)
		} else if (!menuIsOpen && group.current.position.z > -10) {
			group.current.position.z -= 0.3
		} else if (!menuIsOpen && group.current.position.z <= -10 && group.current.visible === true) {
			group.current.visible = false
		} 
		
		if (menuStateCurrentName === 'main' && group.current.position.z <= 0 && group.current.visible === false) {
			group.current.position.z += 0.1
			group.current.visible = true
		}
	})

	return (
		<group ref={group} {...props} dispose={null} visible={false}>
			<mesh
				geometry={nodes['firework-solid'].geometry}
				material={materials['Default OBJ']}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</group>
	)
}

// useGLTF.preload('/COLORED-firework-solid_shadeless-transformed.glb')
