/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets-by-page/about/models/new_york_hot-dog_cart-transformed.glb s -T
Author: Outlier Spa (https://sketchfab.com/outlier_spa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-york-hot-dog-cart-d363905ab6db442789acf06e031e2b21
Title: New York Hot-Dog Cart
*/

import React from 'react'
import { useGLTF, BakeShadows } from '@react-three/drei'

export default function Cart() {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/assets-by-page/about/models/new_york_hot-dog_cart-transformed.glb')
  return (
		<group dispose={null}>
			<BakeShadows />
			<group scale={0.1} rotation={[0, -Math.PI / 2, 0]} position={[-28, -4.9, -30]}>
				<mesh
					geometry={nodes['b02_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 30.64, -71.19]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b01_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[4.5, 49.49, 8.94]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e05_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 17.5, -10.26]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b08_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 25.39, -80.46]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a04_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[9.29, 65.43, 8.94]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a06_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-11.31, 65.68, 8.94]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b05_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[9.41, 65.73, -43.8]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a05_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[9.41, 68.56, -21.94]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a03_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-18.38, 65.4, -28.04]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['c01_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-25.23, 42.03, -7]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['d05_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-25.77, 65.41, -7.52]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['d03_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-25.77, 129.03, -7.52]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['d02_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-25.77, 157.45, -7.52]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a04-2_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[9.29, 73.39, 8.94]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b03_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-11.02, 88.02, -88.61]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b04_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[5.42, 88.65, -52.55]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['d04_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-18.13, 146.67, -76.5]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['d01_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-20.4, 181.95, -69.7]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b06_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[12.44, 47, 23.9]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['c06_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[18.89, 47, 24.2]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b07_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 42.01, -25.43]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e06_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 6.64, -12.71]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e03_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 15.84, -10.26]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e02_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 10.08, -11.15]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e04_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 15.16, -10.26]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['c02_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-1.31, 75.35, -36.61]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['c03_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-1.31, 75.36, -75.26]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['c04_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 42.01, -41.35]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a02_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-13.29, 65.1, -63.57]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['a01_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-20.45, 66.33, -63.57]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['c05_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[-20.66, 83.97, -79.91]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e07_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 14.66, -80.46]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['e01_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 14.84, -80.28]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['b09_low_hot-dog_0'].geometry}
					material={materials['hot-dog']}
					position={[0, 16.88, -80.27]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.ketchup_low001_props_0.geometry}
					material={materials.props}
					position={[7.25, 74.8, -22.13]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.mustard_low001_props_0.geometry}
					material={materials.props}
					position={[4.73, 74.8, -30.52]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.pretzel_low001_props_0.geometry}
					material={materials.props}
					position={[9.48, 66.5, 9.66]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['soda-coca-cola_low001_props_0'].geometry}
					material={materials.props}
					position={[17.11, 72.08, -22.37]}
					rotation={[-Math.PI / 2, 0, 0.21]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['soda-sprite_low001_props_0'].geometry}
					material={materials.props}
					position={[15.29, 72.08, -28.9]}
					rotation={[-Math.PI / 2, 0, -0.54]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['soda-sunkist_low001_props_0'].geometry}
					material={materials.props}
					position={[12.19, 72.08, -15.06]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes.pretzel_low002_props_0.geometry}
					material={materials.props}
					position={[9.48, 67.72, 9.18]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['bottle-coca-cola_low003_props_0'].geometry}
					material={materials.props}
					position={[16.91, 112.33, -52.06]}
					rotation={[-Math.PI / 2, 0, -1.06]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['bottle-sprite_low003_props_0'].geometry}
					material={materials.props}
					position={[14.12, 112.81, -64.95]}
					rotation={[-Math.PI / 2, 0, 0.96]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['bottle-sunkist_low003_props_0'].geometry}
					material={materials.props}
					position={[16.91, 112.35, -71.93]}
					rotation={[-Math.PI / 2, 0, 0.3]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['poland-sping_low003_props_0'].geometry}
					material={materials.props}
					position={[16.92, 111.25, -95.08]}
					rotation={[-Math.PI / 2, 0, 2.18]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['poland-sping_low004_props_0'].geometry}
					material={materials.props}
					position={[10.24, 111.25, -84.41]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['poland-sping_low006_props_0'].geometry}
					material={materials.props}
					position={[0.41, 111.25, -91.48]}
					rotation={[-Math.PI / 2, 0, 0.93]}
					scale={100}
					castShadow
					receiveShadow
				/>
				<mesh
					geometry={nodes['bottle-coca-cola_low004_props_0'].geometry}
					material={materials.props}
					position={[10.14, 112.33, -58.22]}
					rotation={[-Math.PI / 2, 0, 0.45]}
					scale={100}
					castShadow
					receiveShadow
				/>
			</group>
		</group>
	)
}

useGLTF.preload(process.env.PUBLIC_URL + '/assets-by-page/about/models/new_york_hot-dog_cart-transformed.glb')
