/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets-by-page/about/models/taxi_with_ad.glb --transform --shadows
*/

import { editable } from '@theatre/r3f'
import { useGLTF } from '@react-three/drei'

export default function Taxi() {
	const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/assets-by-page/about/models/taxi_with_ad-transformed.glb')
	return (
		<editable.group theatreKey='Taxi' scale={25} rotation={[0, Math.PI / 2, 0]} castShadow receiveShadow>
			<mesh geometry={nodes.defaultMaterial004.geometry} material={materials.TaxiCar01Glass} />
			<mesh castShadow geometry={nodes.defaultMaterial005.geometry} material={materials.TaxiCar01}>
				<mesh
					geometry={nodes.BurgerBillboard.geometry}
					material={materials.BurgerBillboard}
					position={[-0.047, 0.28, -0.14]}
					rotation={[Math.PI / 2, -0.32, Math.PI / 2]}
					scale={0.13}
				/>
			</mesh>
			<mesh castShadow receiveShadow geometry={nodes.defaultMaterial002.geometry} material={materials.TaxiCar01} />
			<mesh
				// theatreKey='back-wheel'
				castShadow
				receiveShadow
				geometry={nodes.defaultMaterial.geometry}
				material={materials.TaxiCar01}
				position={[-0.3, -0.2, -0.48]}
			/>
			<mesh castShadow receiveShadow geometry={nodes.defaultMaterial003.geometry} material={materials.TaxiCar01} />
			<editable.mesh
				theatreKey='front-wheel'
				castShadow
				receiveShadow
				geometry={nodes.defaultMaterial001.geometry}
				material={materials.TaxiCar01}
				position={[-0.3, -0.2, 0.61]}
			/>
		</editable.group>
	)
}
